### PR TITLE
Delayed numpy import during setup

### PR DESCRIPTION
**Pull request by maxme1**
Hi!
Great library, but I have trouble installing it because it requires `numpy` to be already installed. 
This PR adds a delayed `numpy` import during setup.

### CODE REVIEW

**Comment by william-silversmith** [comment]
Hi maxme, this is a great addition. Just curious as to what platform/python version you're using as I like to make binaries available.

Will

**Comment by maxme1** [comment]
Hi, Will. Thanks for the quick reply. We're mostly using it on Ubuntu 20.04 with Python 3.10 and 3.11.

**Comment by maxme1** [comment]
@william-silversmith , hi! Sorry to rush you, but could you please release the fixed version to pypi?

**Comment by william-silversmith** [comment]
Hi Max,

Sorry for the delay, I've been on vacation but fortunately today is my
first day back. I'll get that set up for you.

Will

**Comment by william-silversmith** [comment]
Hi Max,

The latest binaries have been uploaded. Thanks for your patience! 

Will

**Comment by maxme1** [comment]
Great. Everything works now. Thank you!

**Pull request merged**
